# Generated by Django 3.2.4 on 2021-06-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABC_Bank', '0002_auto_20210608_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='account_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='balance',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='mobile',
            field=models.BigIntegerField(unique=True),
        ),
    ]
