# Generated by Django 3.2.4 on 2021-06-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABC_Bank', '0003_auto_20210610_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.BigIntegerField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='fromaccount',
            field=models.BigIntegerField(verbose_name='From Account'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='toaccount',
            field=models.BigIntegerField(verbose_name='To Account'),
        ),
    ]
